src/Lodestone/Api.php
src/Lodestone/Modules/Routes.php
src/Lodestone/Modules/XIVDB.php
src/Lodestone/Parser/Achievements.php
src/Lodestone/Parser/CharacterFollowing.php
src/Lodestone/Parser/CharacterFriends.php
src/Lodestone/Parser/FreeCompany.php
src/Lodestone/Parser/FreeCompanyMembers.php
src/Lodestone/Parser/Linkshell.php
src/Lodestone/Parser/Lodestone.php
src/Lodestone/Parser/Search.php
src/Lodestone/UrlBuilder.php

* adds missing $page parameter to various methods
* cleaned up unused variables

chore(parameters): add missing parameters

---

src/Lodestone/Parser/Linkshell.php

Added Linkshell name, when getting its members

Added Linkshell name

---

src/Lodestone/Modules/HttpRequest.php
src/Lodestone/Parser/Achievements.php
src/Lodestone/Parser/Character.php
src/Lodestone/Parser/CharacterFollowing.php
src/Lodestone/Parser/CharacterFriends.php
src/Lodestone/Parser/FreeCompany.php
src/Lodestone/Parser/FreeCompanyMembers.php
src/Lodestone/Parser/Linkshell.php
src/Lodestone/Parser/ParserHelper.php
src/Lodestone/UrlBuilder.php
src/Lodestone/Validator/BaseValidator.php
src/Lodestone/Validator/ValidationException.php

BaseValidator is able to check:
* if an object is initialized
* if an object is not empty
* if an object is an Integer
* if an object is a String
* if an object is an Array
The Validator only throws the first found error.
All errors can be fetched with the
BaseValidator.validateAndFetchErrors() method
Related to: #8

feat(validator): add basic validator

---

src/Lodestone/Validator/BaseValidator.php
src/Lodestone/Validator/ValidationException.php
tests/Lodestone/Validator/BaseValidatorTest.php

the validator can now check if an url begins with http(s)://.
Every absolute url should begin with that.
* used REGEX: ^https?:\/\/
Related to: #17

feat(validator): implement relative url validation

---

src/Lodestone/Validator/CharacterValidator.php

Dashes are valid in names. I am also pretty sure, I saw some other characters in names, but can be wrong on that account.
Also, not sure I like validator throwing fatal errors everywhere. Interrupts my bulk updates on http://simbiat.ru/fftracker =(

Allow dash in names

---

src/Lodestone/Api.php
src/Lodestone/Dom/Element.php
src/Lodestone/Dom/NodeList.php
src/Lodestone/Entities/AbstractEntity.php
src/Lodestone/Entities/Character/Collectable.php
src/Lodestone/Entities/Character/Profile.php
src/Lodestone/Entities/Character/Profile/City.php
src/Lodestone/Entities/Character/Profile/GrandCompany.php
src/Lodestone/Entities/Character/Profile/Guardian.php
src/Lodestone/Modules/Benchmark.php
src/Lodestone/Modules/Logger.php
src/Lodestone/Parser/Character.php
src/Lodestone/Parser/CharacterProfileTrait.php
src/Lodestone/Parser/ParserHelper.php
src/Lodestone/Parser/ParserHelperSpecial.php
tests/bench.php
tests/cli.php

Hope(profile): hope that this increases parsing a profile

---

src/Lodestone/Entities/AbstractEntity.php
src/Lodestone/Entities/Character/Collectable.php
src/Lodestone/Entities/Character/Profile.php
src/Lodestone/Entities/Character/Profile/City.php
src/Lodestone/Entities/Character/Profile/GrandCompany.php
src/Lodestone/Entities/Character/Profile/Guardian.php
src/Lodestone/Parser/Character.php
src/Lodestone/Validator/CharacterValidator.php

* There is now an entity model which allows
to validate each entry of the entity
Related to: #21

refactor(character parser): improve profile parse

---

VALIDATION.md

docs(Validation): create Validation explanation

---

src/Lodestone/Api.php
src/Lodestone/Entities/AbstractEntity.php
src/Lodestone/Entities/Character/Attribute.php
src/Lodestone/Entities/Character/CharacterProfile.php
src/Lodestone/Entities/Character/City.php
src/Lodestone/Entities/Character/ClassJob.php
src/Lodestone/Entities/Character/Collectable.php
src/Lodestone/Entities/Character/Collectables.php
src/Lodestone/Entities/Character/GrandCompany.php
src/Lodestone/Entities/Character/Guardian.php
src/Lodestone/Entities/Character/Item.php
src/Lodestone/Modules/Logger.php
src/Lodestone/Modules/XIVDB.php
src/Lodestone/Parser/Character/TraitAttributes.php
src/Lodestone/Parser/Character/TraitClassJob.php
src/Lodestone/Parser/Character/TraitClassJobActive.php
src/Lodestone/Parser/Character/TraitCollectables.php
src/Lodestone/Parser/Character/TraitGear.php
src/Lodestone/Parser/Character/TraitProfile.php
src/Lodestone/Parser/Html/ParserDocument.php
src/Lodestone/Parser/Html/ParserHtml.php
src/Lodestone/Parser/Lodestone.php

I did some reviews and changed quite some stuff x) All changes are topics for discussion :)
There were also a questions:
1.) Currently the class Hash contains only a hash method for CharacterProfile. Can we move it to CharacterProfile? The Reason for this question is, that I as a user and as a dev would expect that the entity class provides the hash method instead of a Hash class
I tried to improve the materia parsing but my array method was slower than the existing one... maybe you have an idea @viion. Here is the code:
```php
...
// add materia
$materiaNodes = $this->getArrayFromRange('class="db-tooltip__materia', 1, $html);
if ($materiaNodes) {
$entries = explode('</li>', $materiaNodes[0]);
$entries = $this->filterMateriaArray($entries);
foreach ($entries AS $index => $entry) {
$entry …
```

Parser refactor

---

README.md

we missed that while moving hash to CharacterProfile :)

fix(docs): change hashing example

---

src/Lodestone/Parser/Achievements.php
src/Lodestone/Parser/CharacterFollowing.php
src/Lodestone/Parser/CharacterFriends.php
src/Lodestone/Parser/FreeCompanyMembers.php
src/Lodestone/Parser/Html/ParserHelper.php
src/Lodestone/Parser/Lodestone.php
src/Lodestone/Parser/Search.php

* ensureHtml checks now if the html is empty
* use initialize in all possible methods
* cleaned up code for better readability

chore(parser): add empty check to ensureHtml

---

src/Lodestone/Modules/HttpRequest.php
src/Lodestone/Validator/HttpRequestValidator.php

* moved maintenance error in own check
this allows to check for maintenance mode even without checking for http errors or vice versa

chore(Validator): refactor isNotHttperror

---

src/Lodestone/Parser/Character/TraitProfile.php
src/Lodestone/Validator/CharacterValidator.php

Added isset to check for GC to suppress a warning in case there is no GC.

Fix check for GC 

---

CONTRIBUTING.md

This will provide useful informations for all people
who are working on the project
Related to: #36

feat(docs): add contributing guidelines

---

src/Lodestone/Entities/Character/CharacterProfile.php
src/Lodestone/Parser/Character/TraitClassJobActive.php
src/Lodestone/Validator/BaseValidator.php
src/Lodestone/Validator/Exceptions/ValidationException.php
tests/Lodestone/Validator/BaseValidatorTest.php

also contains the changes made to master before :)

Extend empty validation

---

src/Lodestone/Api.php
src/Lodestone/Parser/FreeCompany.php
src/Lodestone/Parser/Linkshell.php

Solves https://github.com/viion/lodestone-php/issues/27
The work to move other entity types into proper classes is a separate task.

Move position of ID to complete refactor for this purpose.

---

docs/ApiCharacters.md
docs/ApiDatabase.md
docs/ApiForums.md
docs/ApiFreeCompany.md
docs/ApiInternals.md
docs/ApiLinkshell.md
docs/ApiLodestone.md
src/Lodestone/Api.php
src/Lodestone/Entities/AbstractEntity.php
src/Lodestone/Entities/FreeCompany/FreeCompany.php
src/Lodestone/Parser/FreeCompany/Parser.php
src/Lodestone/Parser/Html/ParserHelper.php
src/Lodestone/Parser/Linkshell/Parser.php

FC formed returns unix timestamp now (which is consistent with other timestamps available so far)
Removed casting to objects in FC model, which broke toArray (sub-arrays were actually objects, even though array-like)
Defaulted $page to 1, since $page always starts from 1, not from "false"
Fixed ranks grabbing in LinkshellMembers
Fixes and updates in some docs

Small fixes

---

src/Lodestone/Parser/Character/TraitGear.php
src/Lodestone/Parser/FreeCompany/Parser.php

If focus is empty (like in 9234490298434916243) focus is populated by "seeking" and "seeking" becomes empty. This is a fix.

Fix for focus/seeking

---

src/Lodestone/Parser/Character/TraitGear.php

Notice for line 111 was caused by "Cracked Materia" (not sure I know what that even is), which does not have effect in it. Example (at the moment): 1188748

Materia fix

---

src/Lodestone/Api.php

Fixed achievements category
